### ISSUE TITLE
creeperExplosionBehavior gamerule isn't listed in /gamerule command

### ISSUE THREAD

**Issue by vico93** [Devan-Kerman/ServersideCreeperControlFabric#1]
I'm trying to run this mod in my 1.20.4 singleplayer modpack, in a map with commands enabled. But the `creeperExplosionBehavior` isnt showing in the `/gamerule` command.

I'm clueless to figure out what is causing it.

**Comment by Ueaj-Kerman** [comment]
Version `1.1.0` should fix it

**Comment by vico93** [comment]
Thanks a lot!
