### ISSUE TITLE
Mixin error after updating the mod

### ISSUE THREAD

**Issue by vico93** [Devan-Kerman/ServersideCreeperControlFabric#2]
Me again! Sorry for that.

After updating to 1.1.0 i got this strange error trying to start the game. It didn't generate a crash report, so only the latest.log showed that.

[Here's the gist.](https://gist.github.com/vico93/2b57ca3701751c3112ca49f3fa3e3a21)

It mentions [c2me](https://modrinth.com/mod/c2me-fabric/) as well but i didn't touched this mod lately. So i'm reporting here first to see if SSCC could be the case.

**Comment by Ueaj-Kerman** [comment]
oops

**Comment by Ueaj-Kerman** [comment]
1.1.1
